name: watinsup
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  cloud_firestore: ^4.8.3
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.6.1
  enough_giphy_flutter: ^0.4.0
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.7
  flutter_riverpod: ^2.3.6
  flutter_sound: ^9.2.13
  image_picker: ^1.0.1
  intl: ^0.18.1
  path_provider: ^2.1.0
  permission_handler: ^9.2.0
  swipe_to: ^1.0.2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
